# Generated by Django 6.0.3 on 2026-04-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstat',
            name='own_goals',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
