# Generated by Django 6.0.3 on 2026-04-06 02:55

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('format', models.CharField(choices=[('round_robin', 'Round Robin'), ('knockout', 'Knockout'), ('hybrid', 'Hybrid (Group stage + Knockout)')], default='round_robin', max_length=20)),
                ('max_teams', models.IntegerField(choices=[(4, '4'), (8, '8'), (16, '16'), (32, '32')], default=8)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('registration', 'Registration open'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('registration_deadline', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('tiebreaker_rules', models.JSONField(default=list, help_text='Ordered list e.g. ["goal_difference", "head_to_head", "cards"]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveSmallIntegerField(help_text='Round within the tournament (1-indexed).')),
                ('stage', models.CharField(choices=[('group', 'Group stage'), ('knockout', 'Knockout'), ('final', 'Final')], default='group', help_text='Stage of the tournament this fixture belongs to.', max_length=20)),
                ('match_date', models.DateTimeField(blank=True, null=True)),
                ('submission_deadline', models.DateTimeField(blank=True, help_text='Auto-set to 24h after match_date. Admin alerted if no result by this time.', null=True)),
                ('is_bye', models.BooleanField(default=False, help_text='True for bye fixtures generated in uneven brackets.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_fixtures', to='accounts.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_fixtures', to='accounts.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='tournament.tournament')),
            ],
            options={
                'ordering': ['round_number', 'match_date'],
                'unique_together': {('tournament', 'home_team', 'away_team', 'round_number')},
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_score', models.PositiveSmallIntegerField()),
                ('away_score', models.PositiveSmallIntegerField()),
                ('screenshot', cloudinary.models.CloudinaryField(help_text='Proof screenshot uploaded by the submitting team.', max_length=255, verbose_name='result_screenshot')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disputed', 'Disputed')], default='pending', max_length=15)),
                ('admin_note', models.TextField(blank=True, help_text='Admin note shown to submitter when result is rejected.')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='tournament.fixture')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_results', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='TournamentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.PositiveSmallIntegerField(blank=True, help_text='Bracket seed assigned by admin.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_entries', to='accounts.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='tournament.tournament')),
            ],
            options={
                'ordering': ['seed', 'registered_at'],
                'unique_together': {('tournament', 'team')},
            },
        ),
    ]
