# Generated by Django 6.0.3 on 2026-04-07 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_teammembership_history_constraints'),
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='away_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_fixtures', to='accounts.team'),
        ),
    ]
