# Generated by Django 6.0.3 on 2026-05-03 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0015_alter_announcement_options_announcement_is_pinned_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_type', models.CharField(choices=[('result_issue', 'Result issue'), ('schedule_issue', 'Schedule issue'), ('team_player_issue', 'Team/player issue'), ('general_request', 'General request')], max_length=25)),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under review'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='open', max_length=20)),
                ('subject', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('staff_response', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fixture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='tournament.fixture')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL)),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_complaints', to=settings.AUTH_USER_MODEL)),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='tournament.result')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['player', 'status', '-created_at'], name='tournament__player__ba7f38_idx'), models.Index(fields=['status', '-created_at'], name='tournament__status_9e2cd1_idx')],
            },
        ),
    ]
