# Generated by Django 6.0.3 on 2026-04-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='in_game_name',
            field=models.CharField(blank=True, help_text='Your in-game username (PSN / Xbox / EA tag). Set from your dashboard.', max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='unique_id',
            field=models.CharField(blank=True, help_text='Short public player ID. Auto-generated on signup, editable later.', max_length=20, unique=True),
        ),
    ]
