# Generated by Django 6.0.3 on 2026-04-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_player_in_game_name_alter_player_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Admin must approve a team before it can join a tournament.'),
        ),
    ]
