# Generated by Codex on 2026-04-07

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_team_is_approved"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="teammembership",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="teammembership",
            constraint=models.UniqueConstraint(
                condition=Q(is_active=True),
                fields=("player", "team"),
                name="unique_active_membership_per_player_team",
            ),
        ),
        migrations.AddConstraint(
            model_name="teammembership",
            constraint=models.UniqueConstraint(
                condition=Q(is_active=True),
                fields=("player",),
                name="unique_active_membership_per_player",
            ),
        ),
    ]
