# Generated by Codex on 2026-05-02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_teammembership_history_constraints"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(max_length=160),
                ),
                ("message", models.TextField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("registration_submitted", "Registration submitted"),
                            ("registration_approved", "Registration approved"),
                            ("registration_rejected", "Registration rejected"),
                            ("tournament_registration_submitted", "Tournament registration submitted"),
                            ("tournament_registration_approved", "Tournament registration approved"),
                            ("tournament_registration_rejected", "Tournament registration rejected"),
                            ("result_submitted", "Result submitted"),
                            ("result_approved", "Result approved"),
                            ("result_rejected", "Result rejected"),
                            ("result_disputed", "Result disputed"),
                            ("opponent_response", "Opponent response"),
                            ("opponent_score_conflict", "Opponent score conflict"),
                            ("fixture_scheduled", "Fixture scheduled"),
                        ],
                        max_length=64,
                    ),
                ),
                ("url", models.CharField(blank=True, max_length=255)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
            },
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["user", "is_read", "-created_at"], name="accounts_no_user_id_b29cd4_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["kind", "url"], name="accounts_no_kind_7a452d_idx"),
        ),
    ]
