# Generated by Django 6.0.3 on 2026-05-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('registration_submitted', 'Registration submitted'), ('registration_approved', 'Registration approved'), ('registration_rejected', 'Registration rejected'), ('tournament_registration_submitted', 'Tournament registration submitted'), ('tournament_registration_approved', 'Tournament registration approved'), ('tournament_registration_rejected', 'Tournament registration rejected'), ('result_submitted', 'Result submitted'), ('result_approved', 'Result approved'), ('result_rejected', 'Result rejected'), ('result_disputed', 'Result disputed'), ('opponent_response', 'Opponent response'), ('opponent_score_conflict', 'Opponent score conflict'), ('fixture_scheduled', 'Fixture scheduled'), ('complaint_response', 'Complaint response')], max_length=64),
        ),
    ]
