# Generated by Django 6.0.3 on 2026-05-04 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_notification_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('registration_submitted', 'Registration submitted'), ('registration_approved', 'Registration approved'), ('registration_rejected', 'Registration rejected'), ('tournament_registration_submitted', 'Tournament registration submitted'), ('tournament_registration_approved', 'Tournament registration approved'), ('tournament_registration_rejected', 'Tournament registration rejected'), ('result_submitted', 'Result submitted'), ('result_approved', 'Result approved'), ('result_rejected', 'Result rejected'), ('result_disputed', 'Result disputed'), ('opponent_response', 'Opponent response'), ('opponent_score_conflict', 'Opponent score conflict'), ('fixture_scheduled', 'Fixture scheduled'), ('complaint_response', 'Complaint response'), ('marketplace_invite', 'Marketplace invite'), ('marketplace_invite_accepted', 'Marketplace invite accepted'), ('marketplace_invite_rejected', 'Marketplace invite rejected'), ('marketplace_assignment', 'Marketplace assignment')], max_length=64),
        ),
        migrations.CreateModel(
            name='TeamInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_marketplace_invitations', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_invitations', to=settings.AUTH_USER_MODEL)),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_marketplace_invitations', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_invitations', to='accounts.team')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['player', 'status', '-created_at'], name='accounts_te_player__a1bba0_idx'), models.Index(fields=['team', 'status', '-created_at'], name='accounts_te_team_id_76ef41_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('team', 'player'), name='unique_pending_marketplace_invite_per_team_player')],
            },
        ),
    ]
